name: main

on:
    push:
        branches-ignore:
        - nightly

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-01-16
          override: true

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential wabt

      - name: Setup
        run: make prepare

      - name: Run clippy and fmt
        run:  rustup component add clippy --toolchain nightly-2023-01-16-x86_64-unknown-linux-gnu; rustup component add rustfmt --toolchain nightly-2023-01-16-x86_64-unknown-linux-gnu ; make check-lint

      - name: Build
        run: rustup target add wasm32-unknown-unknown ; make build-contract
